services:
  couchdb:
    image: apache/couchdb:3
    container_name: get-it-done-couch
    hostname: getitdone
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./couch_data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.d/local.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - reverse_proxy_network
      - default

networks:
  default:
  reverse_proxy_network:
    external: true